### PR TITLE
Patch 25

### PR DESCRIPTION
**Pull request by dzikakis**
This is causing an issue "can't cast Null value to value of type [struct]". setting the data argument to type ANY fixes it so it can accept nulls. Noticed this when trying to add something to the cart from the front end.

### CODE REVIEW

**Comment by rmarchandTen24** [comment]
Hi Dave,
can you tell me the action you called when you received the error?

**Comment by rmarchandTen24** [comment]
i know you said add to cart but I wanted to know was it public:cart.addOrderItem?

**Comment by dzikakis** [comment]
Pretty sure it was public:cart.addOrderItem as that's all I think I use on the front, it was last week that I ran into this, I can double check again shortly.

**Comment by rmarchandTen24** [comment]
I think that maybe line 121 of cart.cfc should have been declared a struct
and maybe that is the cause of the issue?

https://github.com/ten24/slatwall/blob/master/public/controllers/cart.cfc#L121

**Comment by rmarchandTen24** [comment]
(required any rc) should be (required struct rc) me thinks

**Comment by dzikakis** [comment]
Taking another look at this.. I think it might be the MuraEventHandler that needs updating. ?

**Comment by dzikakis** [comment]
Could also just change the argument to: struct data={}, so the default is an empty struct. I have no idea if anyone would have created an integration that calls doAction() ?

**Pull request closed without merging**
