### PR TITLE
New Payment Integration - Merchant e-Solutions

### PR DESCRIPTION
**Pull request by Squeebly-Joe**
I had to write an integration for this processor for a project, so why not contribute it? I believe I have all the transaction types need by Slatwall set up, but let me know if I missed anything.

Here's processor website: https://www.merchante-solutions.com/
And their developer site: http://developer.merchante-solutions.com/

You'll need to sign up for a sandbox account to test the integration; there's a signup link on the developer.

### CODE REVIEW

**Comment by gregmoser** [comment]
Hi Marcus, this looks great.  I just need to send you over a contributor agreement before we can merge this in.  We only need this once and then we can accept all future pull requests.  If you can just reply with your email address or email me directly at greg.moser@ten24web.com I can get the agreement over to you.

Thanks!

**Comment by gregmoser** [comment]
Also, one other quick note.  If you can make pull requests into the 'feature' branch would would appreciate that.  This way we can get it merged in and run through our QA process before it ends up in master.  Typically new functionality like this will come out in the next dot release.

**Comment by Squeebly-Joe** [comment]
OK sounds good, Greg. I'll shoot you an email after I post this, and I'll be sure to make future pull requests on the feature branch.

**Comment by gregmoser** [comment]
Please just re-issue this PR for the 'feature' branch.

**Pull request closed without merging**
