### PR TITLE
made changes in unit tests of inventoryDAOTest cfc file

### PR DESCRIPTION
**Pull request by mfsi-nirmitm**
made changes in unit tests of InventoryDAOTest  cfc file for solving the error issue : coldfusion.runtime.UninitializedValueException: Value must be initialized before use

### CODE REVIEW

**Comment by mfsi-nirmitm** [comment]
Hi @migueltarga,  where may i found setting for currencycode ?

**Comment by mfsi-nirmitm** [comment]
Okay Thanks. i got it.

**Comment by migueltarga** [comment]
Sorry, its ok to be USD, I didn't realized that all the code was unit test.

**Comment by mfsi-nirmitm** [comment]
Okay np :)

**Pull request merged**
