### PR TITLE
Upgraded templates to Boostrap 3

### PR DESCRIPTION
**Pull request by Squeebly-Joe**
Changed the JS/CSS and updated the classes and markup to the Boostrap 3 versions. 

The edit functions on the account page don't work anymore though; it may be a CSS issue but I'm not sure.

---
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4315)

### CODE REVIEW

**Comment by Squeebly-Joe** [comment]
I've fixed an error in the Merchant e-Solutions integration. It automatically added the change to this pull request, and I'm not sure how to make a new request without closing this one. Let me know if I need to something else to get the fix included.

**Comment by Squeebly-Joe** [comment]
I fixed an issue with the Merchant e-Solutions integration that caused order fulfillment to fail for guest accounts. It automatically included it in this pull request; do I need to do something different to get the fix included or this OK?

**Comment by gregmoser** [comment]
When doing multiple fixes it's best to do them on separate branches and issues separate pull requests.  There are still some issues with the Bootstrap3 implementation so your other changes can't get merged in.

**Comment by Squeebly-Joe** [comment]
I'm still kind of new when it comes to using GitHub; I thought I'd be able to open a new request for the fix. Should I close this request and open a new one for just the fix in the integration, or just leave it until the template issues are worked out?

**Comment by gregmoser** [comment]
I would close this PR, and open 2 new PR's where you have each set of code
changes on it's own branch.

On Thu, Apr 14, 2016 at 1:55 PM Marcus Coia <notifications@github.com>
wrote:

> I'm still kind of new when it comes to using GitHub; I thought I'd be able
> to open a new request for the fix. Should I close this request and open a
> new one for just the fix in the integration, or just leave it until the
> template issues are worked out?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ten24/slatwall/pull/4315#issuecomment-210145688>
>
-- 
*Greg Moser*
Slatwall Product Manager | ten24 Digital Solutions
http://www.slatwallcommerce.com
http://www.ten24web.com

mobile    |  760.518.5314
office    |  877.886.5806 x107

**Pull request closed without merging**
