### PR TITLE
making option code required

### PR DESCRIPTION
**Pull request by jasperboyd**
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4360)

### CODE REVIEW

**Comment by gregmoser** [comment]
You need to also add unique = true...

**Comment by gregmoser** [comment]
Look at how optionGroupCode is implemented

**Comment by jasperboyd** [comment]
Yep my bad, it's there now

**Comment by migueltarga** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ten24/slatwall/4360)*

**Pull request merged**
