### PR TITLE
Added test API URL setting

### PR DESCRIPTION
**Pull request by Squeebly-Joe**
Added a setting so that the URLs for the test and live modes can be different.

---
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4561)

### CODE REVIEW

**Comment by rmarchandTen24** [comment]
thanks Joe

**Comment by rmarchandTen24** [comment]
Just a heads up Joe. We have 4.5 scheduled for release soon however I can't include the merchant solutions integration. This has to do with the need for testing involved PADSS certification and Slatwall. The work is good and will certainly make it into integration services at some point but we aren't able to do it as quickly as other things because it involves payment services. Just wanted to give you a heads up in case you need to add a custom exclude in your git project.

https://github.com/ten24/slatwall/pull/4563

**Comment by rmarchandTen24** [comment]
Also I made a branch with all your changes staged for develop so when the time comes, we can merged it in. https://github.com/ten24/slatwall/pull/4564

**Comment by Squeebly-Joe** [comment]
OK, thanks for letting me know Ryan.

**Pull request merged**
