### PR TITLE
Hotfix ck smartlist unique flag

### PR DESCRIPTION
**Pull request by christopher-kundrat**
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4553)

### CODE REVIEW

**Comment by sumitverma** [comment]
What is this for? Smartlist is a list (array) and I don't think it makes sense to use it return unique object.

**Comment by rmarchandTen24** [comment]
this could be useful when returning 1 record. Can we get guard rails where unique will be false if the pageShow is greater than 1 though

**Comment by sumitverma** [comment]
But the purpose of smartlist is to get a list (getRecords). Also, adding unique criteria will throw error when more than one record is found. 

If you really need this, you can do something like this:

if(arraylen(variables.pageRecords) == 1 && arguments.unique == true {
return variables.pageRecords[1];
}

But even that I won't recommend, because the function can now return array OR object and you will need to check that in the code that call smartlist anyways.

**Comment by rmarchandTen24** [comment]
yeah preseving the return type as array will keep the function pure and make less cases to test. I think you're right, If we want a quick function to get one record it should be a seperate function that could use the smartlist api to figure out how to render the data as unique

**Comment by sumitverma** [comment]
Ya, maybe something like smartlist.getFirstRecord() because smartlist has
no way guarantee 1 unique record.

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Pull request closed without merging**
