### PR TITLE
wrapped all precisionEvaluate calls in val() except calls internal to…

### PR DESCRIPTION
**Pull request by gerickson808**
… another precisionEvaluate

---
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/5158)

### CODE REVIEW

**Comment by rmarchandTen24** [comment]
@gregmoser The nuance is a bit lost on me? What do the quotes do here?

val(precisionEvaluate("round(price * val(getQuantity()) * 100) / 100"));

**Comment by sumitverma** [comment]
It was based on lot of testing we had done and the fact that
precisionevaluate expects a string expression. But, we can skip adding
quotes, because based on documentation it is more performant to not add
quotes.

https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/precisionevaluate.html

**Comment by dzikakis** [comment]
FYI: The question of quotes brought back some recollection of this: https://groups.google.com/forum/#!searchin/slatwallecommerce/precisionEvaluate%7Csort:relevance/slatwallecommerce/t3znQ7XcDAI/ydD-JWcgKQQJ 

Seems it was a pre-4.2 Railo issue

**Comment by gregmoser** [comment]
@rmarchandTen24 and @sumitverma the quotes are important because without them it is inconsistent between Adobe & Lucee as not both engines perform the same style of type check optimization.

**Pull request merged**
