### PR TITLE
removing reference to session

### PR DESCRIPTION
**Pull request by rmarchandTen24**
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/5261)

### CODE REVIEW

**Comment by sumitverma** [comment]
@rmarchandTen24 This wont work, because application is still server specific.

**Comment by gregmoser** [comment]
Also this would cause MAJOR issues because everyone's collections would be in the same application scope... application.collection would get updated in mid-request if someone else instantiated a collection entity.

**Comment by gregmoser** [comment]
shouldn't this use: HibachiCacheService.getCachedValue() / setCachedValue() / hasCachedValue() so that you can point multiple application servers to the same cache storage

**Comment by sumitverma** [comment]
Goal is to have it to work out of the box with multiple application server
without having a shared cache storage.

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Pull request merged**
