### PR TITLE
adding rounding for promotion processing

### PR DESCRIPTION
**Pull request by jasperboyd**
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4403)

### CODE REVIEW

**Comment by gregmoser** [comment]
CAST() doesn't work on all DB's.  Need to verify on MS SQL, MySQL & Oracle

**Comment by brucebailey** [comment]
Due to an overwhelming number of junk messages, this email address is walking among the dead.

If you are a real person with a real message for me, please resend to bailey at movementdh dot com.  

Thank you!

**Comment by jasperboyd** [comment]
@gregmoser there are other cast statements in code outside of this diff, we should probably look if those are currently causing problems as well

**Comment by gregmoser** [comment]
Ok, it may be fine... but you certainly need to check before merging it in.  You should be able to test MySQL and MS SQL... @ian-a-hickey can help you run it against Oracle.

**Comment by jasperboyd** [comment]
@gregmoser Ian's confirmed this is okay on oracle, I've already tested on mysql and mssql and found it to fix the bug

**Comment by gregmoser** [comment]
Ok, great!  Then merge away.  I must have been mistaken with CAST() being a compatibility issue.

Thanks for testing.

**Comment by jasperboyd** [comment]
In some cases it would matter "CAST does not support LONG, LONG RAW, or the Oracle-supplied types." but Decimal is an Ansi SQL Type

**Comment by gregmoser** [comment]
Oh ok... so I was only "mostly" wrong :)

**Comment by migueltarga** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ten24/slatwall/4403)*

**Comment by gregmoser** [comment]
Still an issue here.  CAST & ROUND don't make sense together.  Round() is a ColdFusion function, but it is being used in SQL.

Also, I don't think that you can use CAST as a replacement for ROUND, because it has different behavior... it truncates.

We should probably discuss solution as a group at this point

**Comment by jasperboyd** [comment]
@gregmoser round is a sql function too

**Comment by gregmoser** [comment]
Then we shouldn't need the cast right?

**Comment by jasperboyd** [comment]
I was replicating the implementation of L827-828 it might be a redundancy, but it seems like a good safeguard against none currency decimal values, worst case scenario it returns what it was going to return anyway, best case it strips a .001 that could hose the whole order process

**Comment by gregmoser** [comment]
Ok, well the round() right now is in the wrong spot.  the way it is right now, it's going to round() then * 100 then / 100

right now it's

```
CAST( ((round(originalPrice - (originalPrice * (discountAmount / 100)))*100)/100) AS DECIMAL(19,2) )
```

Shouldn't it be

```
CAST( ( round( ( originalPrice - (originalPrice * (discountAmount / 100) ) ) * 100 ) / 100 ) AS DECIMAL(19,2) )
```

And I still get nervous about truncation so I'd rather just see an error.  With that being said I would make it

```
round( (originalPrice - (originalPrice * (discountAmount / 100) ) ) *100 ) / 100
```

**Comment by jasperboyd** [comment]
That was my mistake, I thought the first example was our convention for rounding operations.

I'm not sure what makes you nervous, if a hard error was thrown it would be one thing, but all the user sees is 'invalid payment amount', with a $0 payment amount due, It takes some writedumping to discover the rounding error.

**Comment by gregmoser** [comment]
The conversation has turned purely academic at this point, but I will continue just for arguments sake.  I don't really care at this point, but I will make my points anyway.

1) If you for example do CAST(19.99999, DECIMAL(19,2)) the net result will be 19.99.  However when doing a round (as in all other promotion math) the result is 20.00

2) If you state that it will never be 19.99999 BECAUSE of the previous round, then what is the point of the CAST()?  It's just adding additional processing overhead.

**Comment by jasperboyd** [comment]
I think the academia is worthwhile I wanted to understand this one, my original thought was the cast was a safeguard against the * 100 / 100 operation only because of the devision, but if that belongs in the round then I see what you're saying and the cast is superfluous. 

I was basing this implementation and understanding from L548, L584, L696, L742 which are implemented a little differently * 100 being the last operation and outside of the round. I'll make the revision you describe, do you think anything should be changed with those?

Thanks for baring with me on this one!

**Pull request closed without merging**
