### PR TITLE
add an orderitem using skuCode instead of skuID

### PR DESCRIPTION
**Pull request by ian-a-hickey**
adds the ability to use skuCode to add orderItems instead of skuID.

---
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4875)

### CODE REVIEW

**Comment by ian-a-hickey** [comment]
Closing as this is already in develop.

**Comment by sumitverma** [comment]
Need this in hotfix

**Comment by gregmoser** [comment]
Can we add by productCode as well?  It would be helpful if the product only has 1 sku.

**Comment by sumitverma** [comment]
I think it might cause confusion because we will need to add the default
sku to cart.

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Comment by dzikakis** [comment]
@gregmoser @sumitverma 

This caught my eye.  Just yesterday I was seeing if you could add a product to a cart for wishlist functionality similar to what they have on: https://www.blksport.co.uk/

Basically a cart with some pending requirements - size/color selections.

Thought it was interesting.

**Pull request merged**
