### PR TITLE
Fixes stockAdjustmentItems display for physicals

### PR DESCRIPTION
**Pull request by gregmoser**

### CODE REVIEW

**Comment by gregmoser** [comment]
This PR, fixes the issues brought up on this thread:
https://groups.google.com/d/msg/slatwallecommerce/aRsCrAUPcTE/eUwL258RCgAJ

However, it still needs to be tested.

**Comment by pauaware** [comment]
Hi Greg,

Faulted on line 71, but the replacement snippet below runs and shows Stock Adjustments.

I took a punt and ran with tostock.sku.

```
<cfelseif listFindNoCase("satPhysicalCount", rc.stockAdjustment.getStockAdjustmentType().getSystemCode())>
		<hb:HibachiListingColumn tdclass="primary" propertyIdentifier="tostock.sku.skucode" />
		<hb:HibachiListingColumn propertyIdentifier="tostock.sku.product.brand.brandName" />
		<hb:HibachiListingColumn propertyIdentifier="tostock.sku.product.productName" />
		<hb:HibachiListingColumn propertyIdentifier="tostock.sku.skuDefinition" sort="false" />
```

**Comment by gregmoser** [comment]
So, are you saying that now it displays all content in the listing by just switching to "tostock"?

**Comment by gregmoser** [comment]
Also, what was the error that you got with my original code?

**Comment by pauaware** [comment]
Error from original code as below:

**Comment by gregmoser** [comment]
I didn't get the error with your comment.

**Comment by pauaware** [comment]
[dump.html.zip](https://github.com/ten24/slatwall/files/51170/dump.html.zip)

**Pull request merged**
