### PR TITLE
Duplicate Request Token

### PR DESCRIPTION
**Pull request by jasperboyd**
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4383)

### CODE REVIEW

**Comment by migueltarga** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ten24/slatwall/4383)*

**Comment by gregmoser** [comment]
We should really sit down and go through this in depth with @rmarchandTen24 and @sumitverma on a call, because there are a lot of implication.  This first pass already has some "red flags" that I'd want to go over on a call with the other decisions makers.

**Comment by jasperboyd** [comment]
Sounds good to me @gregmoser I just wanted to get some eyes on this.

**Comment by migueltarga** [comment]
Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ten24/slatwall/4383)*

**Pull request closed without merging**
