### PR TITLE
removing category code as required in tax category

### PR DESCRIPTION
**Pull request by jasperboyd**

### CODE REVIEW

**Comment by gregmoser** [comment]
this won't work if you remove 'required' because two records with 'null' will violate the unique constraint.  There is a special validation for 'uniqueOrNull'.

**Comment by gregmoser** [comment]
Take a look at attributeSetCode as an example.

**Comment by jasperboyd** [comment]
Made the changes to this as the other pull. What I'm wondering is when we'd ever want to consider null when determining uniqueness?

**Comment by gregmoser** [comment]
This is just how databases work.




On Wed, Feb 24, 2016 at 12:27 PM Jasper Boyd <notifications@github.com> wrote:
Made the changes to this as the other pull. What I'm wondering is when we'd ever
want to consider null when determining uniqueness?

—
Reply to this email directly or view it on GitHub .


-- Greg Moser Slatwall Product Manager | ten24 Digital Solutions http://www.slatwallcommerce.com http://www.ten24web.com
mobile | 760.518.5314
office | 877.886.5806 x107

**Pull request merged**
