### PR TITLE
PEER REVIEW ONLY: settings are now declared in json files

### PR DESCRIPTION
**Pull request by jasperboyd**
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4195)

### CODE REVIEW

**Comment by gregmoser** [comment]
I believe that this belongs in the model directory, and not the config directory.  In my mind config is all about runtime.  These files have much more to do with the core model of the slatwall application... just like validations and process objects

**Comment by gregmoser** [comment]
Closing, see comments

**Comment by jasperboyd** [comment]
@ryan

**Comment by gregmoser** [comment]
I think you meant @rmarchandTen24

**Comment by gregmoser** [comment]
Jasper, will you update this with the latest feature so that our tests run?

@rmarchandTen24 let me know when you want to talk about this... but I really think that these files belong in the model directory because they define data that gets stored against the model.  Config is really supposed to be about runtime configuration changes... you can't "opt-out" of settings the same way that you might "opt-out" of default data.

**Comment by gregmoser** [comment]
@jasperboyd is going to re-issue this.

**Comment by jasperboyd** [comment]
@gregmoser please leave this open so I can review the dif as I push to this branch

**Comment by gregmoser** [comment]
Sorry @jasperboyd my bad

**Comment by gregmoser** [comment]
@jasperboyd I think that it makes more sense for the integration settings to live in a folder like this:

```
/integrationServices/authorizenet/model/settings/authorizenet.json
```

This way we can allow for integrations to define other types of settings that are actually applied to maybe "Products" or "Accounts"

```
/integrationServices/authorizenet/model/settings/authorizenet.json
/integrationServices/authorizenet/model/settings/product.json
/integrationServices/authorizenet/model/settings/account.json
```

We actually have some specs for upcoming features that require this functionality where an integration extends the settings of other objects and thats why I think it makes sense to standardize on where all  settings are kept for integrations.

**Comment by rmarchandTen24** [comment]
Reviewed 81 of 81 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ten24/slatwall/4195)*

**Comment by rmarchandTen24** [comment]
hey jasper, can i get you to re-issue this into develop

**Pull request closed without merging**
