### PR TITLE
Mitrah test cases

### PR DESCRIPTION
**Pull request by cfmitrah**

### CODE REVIEW

**Comment by rmarchandTen24** [comment]
@cfmitrah For us to be able to merge this we will need you to sign our contributer agreement. Please DM me and I will send the document.

**Comment by cfmitrah** [comment]
@rmarchandTen24 I didn't see your mail id in your GitHub profile to DM you, are you in CFML slack please ping me there my slack handle is @mitrahsoft  I recommend to use https://cla-assistant.io/ as MuraCMS guys are doing for this.

**Comment by rmarchandTen24** [comment]
@cfmitrah you can DM me at ryan.marchand@ten24web.com

**Comment by cfmitrah** [comment]
@rmarchandTen24 sent you the signed contributor's agreement.

**Comment by migueltarga** [comment]
most of the unit tests in this PR has no value for the application. Not realistic tests, just data type checks based on the function return type...

**Comment by cfmitrah** [comment]
@migueltarga I partially agree with you, we can't build the entire unit test cases in a day. If you could provide some guidelines to add some realistic tests, I am so happy to contribute more.

**Pull request closed without merging**
