### PR TITLE
Develop pj add email and address type to vendor address

### PR DESCRIPTION
**Pull request by pjohn1024**

### CODE REVIEW

**Comment by rmarchandTen24** [comment]
@pjohn1024 @sumitverma this looks like an opportunity to get email address into the slatwalladdress tag. I mean it seems reasonable to me that if the address.cfc has emailaddress the tag should too.

**Comment by pjohn1024** [comment]
@rmarchandTen24 Sure, I can make that change @sumitverma Please let us know what you think.

**Comment by sumitverma** [comment]
Sure, makes sense to me.

**Comment by pjohn1024** [comment]
@rmarchandTen24 My bad...Email address was already in the tag. So cleaned it up.

**Pull request merged**
