### PR TITLE
Update Shipping Service

### PR DESCRIPTION
**Pull request by ian-a-hickey**
Found this on startup of latest stable in a custom project. Wrapping it fixes it.

---
This change is [Reviewable](https://reviewable.io/reviews/ten24/slatwall/4915)

### CODE REVIEW

**Comment by gregmoser** [comment]
This fix makes no sense, and it leads me to believe that there is another issue going on.  We check on the line above to make sure that the shipping method rate has a shipping integration.  Why isn't the function returning one?

**Comment by gregmoser** [comment]
@rmarchandTen24 and @sumitverma I think I need a lesson on how to officially "review" pull requests so that you get the feedback.

**Comment by sumitverma** [comment]
If you look at the method getIntegrationByOrderFulfillmentAndShippingMethodRate it doesn't return integration if the rate is not usable. So, the fix looks ok to me...

@gregmoser When you comment inline on the code it gives you the option to review vs just comment.

**Comment by gregmoser** [comment]
Gotcha, ok cool.  So what should I do?  Review or Comment?

**Comment by ten24git** [comment]
Review allows you to do multiple comment as one set of review. It also
allows you to require change / approval before merge. So, you can review or
comment based on whatever makes sense.

Sumit Verma
Partner / Vice President | ten24, LLC
office: 877.886.5806 x 103 | mobile: 617.290.8214
www.ten24web.com | www.linkedin.com/in/sverma | twitter: blogonria

**Comment by pauaware** [comment]
Further to my commit today re #4922 OrderService, the ShippingService was the next break in my code on 4.5.016. This is what I did to restore a working external shipping service in the getIntegrationsByOrderFulfillmentAndShippingMethods method:

`if( !isNull(shippingMethodRate.getShippingIntegration()) && shippingMethodRate.getShippingIntegration().getActiveFlag() ){
					
					var shippingIntegration = getIntegrationByOrderFulfillmentAndShippingMethodRate(arguments.orderFulfillment,shippingMethodRate);
					
					//shippingIntegration may not return a usable integration
					//this line moved into block FIX below 
					//shippingIntegration.getIntegrationCFC("shipping").addEligibleShippingMethodRate(shippingMethodRate);
					
					if(!isNull(shippingIntegration) && !arrayFind(integrations, shippingIntegration)){
						
						//FIX. integration method call moved to after null test
						shippingIntegration.getIntegrationCFC("shipping").addEligibleShippingMethodRate(shippingMethodRate);

						arrayAppend(integrations,shippingIntegration);
					}
				}
`

**Pull request merged**
